services:
  nginx:
    image: nginx:stable-alpine
    container_name: file-verification-api-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:9.0
    container_name: file-verification-api-mysql
    restart: unless-stopped
    command: --max_allowed_packet=16M
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel

  php:
    container_name: file-verification-api-php
    restart: unless-stopped
    build: docker/php
    links:
      - mysql
    volumes:
      - ./src:/var/www/html
      - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - mysql